apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: webnull-test-delay
spec:
  destination:
    name: webnull
  precedence: 3
  match:
    request:
      headers:
        method:
          exact: GET
  httpFault:
    delay:
      fixedDelay: 1.000s
      percent: 5
