apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: webnull-test-bigdelay
spec:
  destination:
    name: webnull
  precedence: 4
  match:
    request:
      headers:
        method:
          exact: GET
  httpFault:
    delay:
      fixedDelay: 4.000s
      percent: 25
