apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: webnull-test-abort
spec:
  destination:
    name: webnull
  precedence: 5
  match:
    request:
      headers:
        method:
          exact: GET
  httpFault:
    abort:
      httpStatus: 400
      percent: 1
