apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webnull
spec:
  hosts:
  - webnull
  http:
  - route:
    - destination:
        host: webnull
    fault:
      delay:
        percent: 5
        fixedDelay: 1s
