apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: webnull-request-timeout
spec:
  destination:
    name: webnull
  precedence: 2
  httpReqTimeout:
    simpleTimeout:
      timeout: 3s
