apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webnull
spec:
  hosts:
  - webnull
  http:
  - route:
    - destination:
        host: webnull
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webnull
spec:
  host: webnull
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http2MaxRequests: 100
        maxRequestsPerConnection: 2
        http1MaxPendingRequests: 50
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 10s
      maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hurl
spec:
  hosts:
  - hurl
  http:
  - route:
    - destination:
        host: hurl
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hurl
spec:
  host: hurl
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
