apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webnull
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webnull
    spec:
      containers:
      - env:
        - name: WEBNULL_CPU
          value: "1"
        image: ancientlore/webnull:0.1
        imagePullPolicy: Always
        name: webnull
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webnull
  labels:
    app: webnull
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: webnull
