apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topdogui-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topdogui
      service: topdogui
      group: v1
  strategy:
    rollingUpdate:
      maxSurge: 60%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: topdogui
        version: v1
        service: topdogui
        group: v1
    spec:
      containers:
      - env:
        - name: MIDTIER
          value: "http://topdogmt:5000"
        - name: BACKEND
          value: "http://topdogbe:5000"
        image: ancientlore/topdog:0.1.1
        imagePullPolicy: Always
        name: topdog
        ports:
        - containerPort: 5000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /backend
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: topdogui
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: topdogui
    service: topdogui
  sessionAffinity: None
  type: ClusterIP
