apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topdogui-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: topdogui
        version: v1
    spec:
      containers:
      - env:
        - name: VERSION
          value: "1"
        - name: MIDTIER
          value: "http://topdogmt:5000"
        - name: BACKEND
          value: "http://topdogbe:5000"
        image: ancientlore/topdog:0.1.1
        imagePullPolicy: Always
        name: topdogui
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: topdogui
  labels:
    app: topdogui
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: topdogui
