apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topdogbe-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topdogbe
      service: topdogbe
      group: v2
  strategy:
    rollingUpdate:
      maxSurge: 60%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: topdogbe
        version: v2
        service: topdogbe
        group: v2
    spec:
      containers:
      - env:
        - name: VERSION
          value: "2"
        image: ancientlore/topdog:0.1.1
        imagePullPolicy: Always
        name: topdog
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: topdogbe
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: topdogbe
    service: topdogbe
  sessionAffinity: None
  type: ClusterIP
