apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topdogbe-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: topdogbe
        version: v2
    spec:
      containers:
      - env:
        - name: VERSION
          value: "2"
        image: ancientlore/topdog:v0.1.2
        imagePullPolicy: Always
        name: topdogbe
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: topdogbe
  labels:
    app: topdogbe
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: topdogbe
