apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: topdogbe-shift
spec:
  destination:
    name: topdogbe
  precedence: 2
  route:
  - labels:
      version: v2
    weight: 50
  - labels:
      version: v3
    weight: 50
