apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: topdogmt-retry
spec:
  destination:
    name: topdogmt
  precedence: 2
  route:
  - labels:
      version: v1
  httpReqRetries:
    simpleRetry:
      attempts: 3
      perTryTimeout: 100ms
