apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: topdogbe
spec:
  hosts:
  - topdogbe
  http:
  - route:
    - destination:
        host: topdogbe
        subset: v2
      weight: 50
    - destination:
        host: topdogbe
        subset: v3
      weight: 50
